linters:
  enable:
    - errcheck
    - gosec
    - staticcheck
    - unused

linters-settings:
  gosec:
    severity: medium  # Must be 'low', 'medium', or 'high'
    excludes:
      - G104  # Corrected exclude property

issues:
  exclude:
    - "error return value not checked"
  max-issues-per-linter: 10
  max-same-issues: 5
  new-from-rev: "HEAD~1"

output:
  formats:
    - format: json
    - format: checkstyle
  print-issued-lines: true
  sort-results: true

run:
  timeout: 2m
  tests: true
  build-tags: ["integration"]  # Must be an array
  allow-parallel-runners: true

severity:
  default-severity: error



# linters:
#   # Disable all linters.
#   # Default: false
#   disable-all: false
#   # Enable specific linter
#   # https://golangci-lint.run/usage/linters/#enabled-by-default
#   enable:
#     - asasalint
#     - asciicheck
#     - bidichk
#     - bodyclose
#     - canonicalheader
#     - containedctx
#     - contextcheck
#     - copyloopvar
#     - cyclop
#     - decorder
#     - depguard
#     - dogsled
#     - dupl
#     - dupword
#     - durationcheck
#     - err113
#     - errcheck
#     - errchkjson
#     - errname
#     - errorlint
#     - exhaustive
#     - exhaustruct
#     - exptostd
#     - fatcontext
#     - forbidigo
#     - forcetypeassert
#     - funlen
#     - gci
#     - ginkgolinter
#     - gocheckcompilerdirectives
#     - gochecknoglobals
#     - gochecknoinits
#     - gochecksumtype
#     - gocognit
#     - goconst
#     - gocritic
#     - gocyclo
#     - godot
#     - godox
#     - gofmt
#     - gofumpt
#     - goheader
#     - goimports
#     - gomoddirectives
#     - gomodguard
#     - goprintffuncname
#     - gosec
#     - gosimple
#     - gosmopolitan
#     - govet
#     - grouper
#     - iface
#     - importas
#     - inamedparam
#     - ineffassign
#     - interfacebloat
#     - intrange
#     - ireturn
#     - lll
#     - loggercheck
#     - maintidx
#     - makezero
#     - mirror
#     - misspell
#     - mnd
#     - musttag
#     - nakedret
#     - nestif
#     - nilerr
#     - nilnesserr
#     - nilnil
#     - nlreturn
#     - noctx
#     - nolintlint
#     - nonamedreturns
#     - nosprintfhostport
#     - paralleltest
#     - perfsprint
#     - prealloc
#     - predeclared
#     - promlinter
#     - protogetter
#     - reassign
#     - recvcheck
#     - revive
#     - rowserrcheck
#     - sloglint
#     - spancheck
#     - sqlclosecheck
#     - staticcheck
#     - stylecheck
#     - tagalign
#     - tagliatelle
#     - testableexamples
#     - testifylint
#     - testpackage
#     - thelper
#     - tparallel
#     - unconvert
#     - unparam
#     - unused
#     - usestdlibvars
#     - usetesting
#     - varnamelen
#     - wastedassign
#     - whitespace
#     - wrapcheck
#     - wsl
#     - zerologlint
#   presets:
#     - bugs
#     - comment
#     - complexity
#     - error
#     - format
#     - import
#     - metalinter
#     - module
#     - performance
#     - sql
#     - style
#     - test
#     - unused
#   # Enable only fast linters from enabled linters set (first run won't be fast)
#   # Default: false
#   fast: true
# # All available settings of specific linters.
# linters-settings:
#   # See the dedicated "linters-settings" documentation section.
#   option: value
# issues:
#   # See the dedicated "issues" documentation section.
#   option: value
# # output configuration options
# output:
#   # See the dedicated "output" documentation section.
#   option: value
# # Options for analysis running.
# run:
#   # See the dedicated "run" documentation section.
#   option: value
# severity:
#   # See the dedicated "severity" documentation section.
#   option: value
