name: Reusable Node Service Workflow
on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      node_version:
        required: true
        type: string

jobs:
  dependency:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}

      - name: Install dependencies and build
        run: |
          cd ${{ inputs.service_name }}
          npm install
          npm run build

# name: dependency-install
# on:
#   workflow_call:  # Allows this workflow to be called from other workflows

# jobs:
#   dependency:
#     runs-on: ubuntu-24.04
#     outputs:
#       version: ${{ steps.get_version.outputs.VERSION }}
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
        
#       - name: Set up Node.js with cache
#         uses: actions/setup-node@v4
#         with:
#           node-version: ${{ inputs.node_version }}
#           cache: "npm"
#           cache-dependency-path: "node/package-lock.json"

#       - name: Read VERSION
#         id: get_version
#         run: |
#           # Read from a VERSION file 
#           VERSION=$(cat node/VERSION | xargs)
#           echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"
#           echo "VERSION is $VERSION"

#       - name: Install dependencies and build
#         run: |
#           cd node
#           npm install
#           npm run build
