name: dependency-install
on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string  # Specific Node.js version per service

    outputs:
      version: ${{ jobs.dependency.outputs.version }}

jobs:
  dependency:
    runs-on: ubuntu-24.04

    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}

      - name: Read VERSION
        id: get_version
        run: |
          VERSION=$(cat node/VERSION | xargs)

          # Set the version output
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"

          echo "Using Node.js version: ${{ inputs.node_version }}"
          echo "Application VERSION: $VERSION"

      - name: Install dependencies and build
        run: |
          cd node
          npm install
          npm run build

# ---
# name: dependency-install
# on:
#   workflow_call:  # Allows this workflow to be called from other workflows

# jobs:
#   dependency:
#     runs-on: ubuntu-24.04
#     outputs:
#       version: ${{ steps.get_version.outputs.VERSION }}
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
        
#       - name: Set up Node.js with cache
#         uses: actions/setup-node@v4
#         with:
#           node-version: "18.12.1"

#       - name: Read VERSION (Set Once)
#         id: get_version
#         run: |
#           # Read from a VERSION file 
#           VERSION=$(cat node/VERSION | xargs)
          
#           # Correct way to set output for reusable workflows
#           echo "VERSION=$VERSION" >> "$GITHUB_ENV"
#           echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"

#           echo "VERSION is $VERSION"

#       - name: Install dependencies and build
#         run: |
#           cd node
#           npm install
#           npm run build
