---
name: dependency-install
on:
  workflow_call:  # Allows this workflow to be called from other workflows

jobs:
  dependency:
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read VERSION (Set Once)
        id: get_version
        run: |
          # Read from a VERSION file 
          VERSION=$(cat node/VERSION | xargs)
          
          # Correct way to set output for reusable workflows
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"

          echo "VERSION is $VERSION"

      - name: Install dependencies and build
        run: |
          cd node
          npm install
          npm run build
