name: Go-Dependency-reusable
on:
  workflow_call:
    inputs:
      service_directory:
        required: true
        type: string
      node_version:
        required: false
        type: string
      go_version:
        required: false
        type: string
      language:
        required: true
        type: string
      cache-dependency-path:
        required: false
        type: string

jobs:
  dependency:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Node.js Setup
      - name: Set up Node.js with cache
        if: ${{ inputs.language == 'node' }} # Condition for Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.version }}
          cache: "npm"
          cache-dependency-path: ${{ inputs.service_directory }}

      - name: Install Node.js dependencies
        if: ${{ inputs.language == 'node' }} # Condition for Node
        run: |
          cd ${{ inputs.service_directory }}
          npm install

      # Go Setup
      - name: Set up Go with cache
        if: ${{ inputs.language == 'go' }} # Condition for Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.version }}
          cache-dependency-path: "${{ inputs.service_directory }}/go.sum"

      - name: Install Go dependencies
        if: ${{ inputs.language == 'go' }} # Condition for Go
        run: |
          cd ${{ inputs.service_directory }}
          go mod tidy
          go mod download

      # - name: Install ESLint
      #   run: |
      #     cd ${{ inputs.service_directory }}
      #     npm install
      #     npm install eslint --save-dev

      # - name: Super-linter
      #   uses: super-linter/super-linter@v7.3.0
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     VALIDATE_ALL_CODEBASE: false
      #     FILTER_REGEX_EXCLUDE: "node_modules/.*"  
