name: Reusable Docker Build & Push Workflow

on:
  workflow_call:
    inputs:
      service_directory:
        required: true
        type: string
      image_name:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_TOKEN:
        required: true
    outputs:
        version:
          description: Application version from VERSION file
          value: ${{ jobs.docker-build-push.outputs.version }}

jobs:
  docker-build-push:
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Read VERSION file
        id: get_version
        run: |
          VERSION=$(cat ${{ inputs.service_directory }}/VERSION | xargs)
          echo "Extracted VERSION: $VERSION"
          echo "version=$VERSION" >> "$GITHUB_ENV"  # Set it as an environment variable
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo $GITHUB_OUTPUT
          echo $GITHUB_ENV

      - name: Build and Push Docker Image
        run: |
          cd ${{ inputs.service_directory }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ inputs.image_name }}:${{ jobs.docker-build-push.outputs.version }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ inputs.image_name }}:${{ jobs.docker-build-push.outputs.version }}
          docker images
