name: CI/CD Pipeline

on:
  push:
    branches:
      - production
    paths:
      - '.github/workflows/go.yml'
      - 'go-project/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.2'

      - name: Install Dependencies
        run: |
          cd go-project
          go mod download

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.8
          working-directory: go-project
          install-mode: none
          
      - name: Run Tests
        run: |
          cd go-project
          go test -v ./...

      - name: Build the Application
        run: |
          cd go-project
          mkdir -p dist
          go build -o dist/main ./...

      # - name: Upload Artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: go-artifact
      #     path: go-project/dist/
      #     if-no-files-found: error

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Read Version from VERSION File
        id: read_version
        run: |
          VERSION=$(cat go-project/VERSION | xargs)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Using version: $VERSION"

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        run: |
          docker buildx build --push --tag manisankardivi/new:${{ env.VERSION }} go-project

      # - name: Update Image Version and Push Changes
      #   run: |
          
      #     git clone https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/manisankar-divi/k8s-repo.git
      #     cd k8s-repo
      
      #     # Update image in manifest.yaml
      #     sed -i "s|image: manisankardivi/new:.*|image: manisankardivi/new:${{ env.VERSION }}|" manifest.yaml
      
      #     # Verify changes
      #     git status
      #     git diff
      
      #     # Configure Git
      #     git config --global user.email "manisankar-divi@gmail.com"
      #     git config --global user.name "manisankar-divi"
      
      #     # Commit and push changes if there’s an update blqw blaw
      #     if git diff --exit-code --quiet; then
      #       echo "No changes to commit."
      #     else
      #       git add manifest.yaml
      #       git commit -m "Updated manifest.yaml with version ${{ env.VERSION }} | GitHub Actions Pipeline"
      #       git push origin main
      #     fi
