# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "production", "main" ]
  pull_request:
    branches: [ "production", "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
    - name: ZAP Scan
      uses: zaproxy/action-baseline@v0.14.0
      with:
        token: ${{ secrets.GH_TOKEN }}
        docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
        target: "http://13.127.21.23:8080"
        cmd_options: '-a'
    
