name: "Zap-Scanning"

on:
  schedule:
    - cron: "0/5 * * * *"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          token: ${{ secrets.GH_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: "http://13.127.21.23:8080"
          cmd_options: '-a'
