on:
  workflow_dispatch:
  schedule:
    # At 01:00.
    - cron:  "*/6 * * * *"

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan ZAP website
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          token: ${{ secrets.GH_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: "http://13.127.21.23:8080"
          cmd_options: '-a'
